spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${rds_mysql_url}
    username: ${rds_mysql_name}
    password: ${rds_mysql_secret}
  session:
    store-type: redis
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: ${redis_url}
    port: 6379
---
jwt:
  secret_key: ${jwt_secret}
  access:
    expiration: 3600000000
  refresh:
    expiration: 1209600000000